# Generated by Django 4.2.10 on 2025-04-12 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('references', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('links', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ComicStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyline', models.TextField()),
                ('target_length', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wiki_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.wikiarticle')),
            ],
        ),
        migrations.CreateModel(
            name='ComicScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.IntegerField()),
                ('prompt', models.TextField()),
                ('image_path', models.ImageField(upload_to='comic_scenes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comic_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.comicstory')),
            ],
            options={
                'ordering': ['scene_number'],
            },
        ),
    ]
