# Generated by Django 4.2 on 2025-04-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_comic_rename_prompt_comicscene_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
